<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.18</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.28</MetalamaVersion>
    <MetalamaPremiumVersion Condition="'$(MetalamaPremiumVersion)' == ''">2026.1.28</MetalamaPremiumVersion>
    <MetalamaSamplesReleaseVersion>2026.1.28</MetalamaSamplesReleaseVersion>
    <MetalamaSamplesReleaseMainVersion>2026.1.28</MetalamaSamplesReleaseMainVersion>
  </PropertyGroup>
</Project>